// ============================================================
// Veyonix Structured Error Codes
// All error codes used across the entire platform.
// Format: DOMAIN_SPECIFIC_ERROR
// ============================================================

export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSE: 'AUTH_REFRESH_TOKEN_REUSE',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_PASSWORD_RECENTLY_USED: 'AUTH_PASSWORD_RECENTLY_USED',
  AUTH_RATE_LIMIT_EXCEEDED: 'AUTH_RATE_LIMIT_EXCEEDED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',

  // Organizations
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_ALREADY_EXISTS: 'ORG_ALREADY_EXISTS',
  ORG_SUBSCRIPTION_REQUIRED: 'ORG_SUBSCRIPTION_REQUIRED',
  ORG_DEVICE_LIMIT_REACHED: 'ORG_DEVICE_LIMIT_REACHED',
  ORG_USER_LIMIT_REACHED: 'ORG_USER_LIMIT_REACHED',

  // Devices
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_ALREADY_ENROLLED: 'DEVICE_ALREADY_ENROLLED',
  DEVICE_NOT_ENROLLED: 'DEVICE_NOT_ENROLLED',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  DEVICE_CERTIFICATE_INVALID: 'DEVICE_CERTIFICATE_INVALID',
  DEVICE_CERTIFICATE_EXPIRED: 'DEVICE_CERTIFICATE_EXPIRED',
  DEVICE_COMMAND_FAILED: 'DEVICE_COMMAND_FAILED',
  DEVICE_COMMAND_TIMEOUT: 'DEVICE_COMMAND_TIMEOUT',

  // Policies
  POLICY_NOT_FOUND: 'POLICY_NOT_FOUND',
  POLICY_VERSION_NOT_FOUND: 'POLICY_VERSION_NOT_FOUND',
  POLICY_ALREADY_ASSIGNED: 'POLICY_ALREADY_ASSIGNED',
  POLICY_CONFLICT: 'POLICY_CONFLICT',

  // Agent
  AGENT_ENROLLMENT_FAILED: 'AGENT_ENROLLMENT_FAILED',
  AGENT_TOKEN_INVALID: 'AGENT_TOKEN_INVALID',
  AGENT_VERSION_UNSUPPORTED: 'AGENT_VERSION_UNSUPPORTED',

  // Invitations
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',

  // Feature Flags
  FEATURE_NOT_ENABLED: 'FEATURE_NOT_ENABLED',
  FEATURE_FLAG_NOT_FOUND: 'FEATURE_FLAG_NOT_FOUND',

  // Subscriptions
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_PAYMENT_FAILED: 'SUBSCRIPTION_PAYMENT_FAILED',

  // Storage
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  STORAGE_FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
  STORAGE_FILE_TOO_LARGE: 'STORAGE_FILE_TOO_LARGE',

  // Webhooks
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  BAD_GATEWAY: 'BAD_GATEWAY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
